### PR TITLE
Support for webpack4

### PR DESCRIPTION
**Pull request by bookwyrm**
Fixes chunk cleanup for stats and uses new hook format for integrating with webpack@4.

### CODE REVIEW

**Comment by AnujRNair** [comment]
Hi @bookwyrm! Thanks for the contribution!

Do you think you'd be able to leave the webpack3 path in place too, so this is compatible with webpack 3 and 4?

An example of how this has been done before is here! https://github.com/slackhq/csp-html-webpack-plugin/blob/master/plugin.js#L138-L154

Again, really appreciate the contribution :)

**Comment by brettsmason** [comment]
Is there any news on this PR at all?
Was hoping to use this in a new Webpack 4 build that I'm working on 😃
If I can help at all getting across the finish line let me know!

**Comment by bookwyrm** [comment]
@brettsmason I just haven't had a chance to get back to this to make the suggested updates so that it works with webpack@3. If you want, you can install from my fork to get the behavior with webpack@4 in your project.

```
npm install --save-dev git+https://github.com/bookwyrm/webpack-extraneous-file-cleanup-plugin.git#webpack4
```

**Comment by brettsmason** [comment]
@bookwyrm Thanks a lot. Just gave it a try and it seems to work perfectly in Webpack 4 with your version.
Look forward to seeing this merged 👍

**Comment by bookwyrm** [comment]
@AnujRNair Just pushed an update to keep webpack3 based on the provided example. I have confirmed that it still works with webpack4 but haven't tested webpack3.

**Comment by AnujRNair** [comment]
Thank you @bookwyrm! I just published a new version to npm with your changes - much appreciated!

**Pull request merged**
