### PR TITLE
adding the paths options

### PR DESCRIPTION
**Pull request by sscaff1**
I wanted to have the option to specify a paths array. If the asset is not in one of the paths specified, then I don't want to have it removed (despite it's size). Let me know if this works for you. I appreciate your feedback.

### CODE REVIEW

**Comment by AnujRNair** [comment]
This is a great addition, thanks for contributing!

**Comment by sscaff1** [comment]
Thank you @AnujRNair! When you get a chance, can you publish an updated version to NPM. I'm currently using this plugin for one of my projects.

**Comment by AnujRNair** [comment]
I just did! https://github.com/AnujRNair/webpack-extraneous-file-cleanup-plugin/releases/tag/v1.0.4

**Comment by sscaff1** [comment]
Awesome. Thank you so much for the quick response!

**Pull request merged**
